version: '3.8'

services:
  speedtest-exporter:
#    image: prometheus-speedtest-exporter:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: speedtest-exporter
    restart: always
    hostname: prometheus-speedtest
    ports:
      - 9469:9469
  prometheus:
    image: prom/prometheus:v2.36.2
    container_name: prometheus
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prom_data:/prometheus
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana
    container_name: grafana2
    restart: always
    ports:
      - '3001:3000'
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - grafana-storage:/var/lib/grafana
volumes:
  grafana-storage: {}
  prom_data:
