version: '3.8'

services:
  speedtest-exporter:
    image: prometheus-speedtest-exporter:latest
    container_name: speedtest-exporter
#    hostname: speedtest-exporter
    restart: unless-stopped
    hostname: prometheus-speedtest
    ports:
      - 9469:9469
  prometheus:
    image: prom/prometheus:v2.36.2
    container_name: prometheus
#    hostname: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana2
    restart: unless-stopped
    ports:
      - '3001:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
volumes:
  grafana-storage: {}
