scrape_configs:
  - job_name: 'Speedtest'
    scrape_interval: 5m
    scrape_timeout: 1m
    metrics_path: /metrics
    params:
      script: [speedtest]
    static_configs:
      - targets:
        - speedtest-exporter:9469
